### ISSUE TITLE
Vega Absolute Vault

### ISSUE THREAD

**Issue by joshmorg1007** [SENG426-Team/vega-web#32]
Description:
User's with the role of customer are able to securely store data (secrets) in the form of text, image, file or encrypted keys. These secrets are encrypted when initially created. The customer are able to create, read, delete and update their own secrets. Customers can also filter their secretes by entry date.

User's with the role of admin are able to see the secrets of all users and can create, read, delete and update all user's secrets. The admin can retrieve statistics regarding Number of added entries in the last 7 days vs. added entries the week before that which include the current days entries as well. Only the admin can access these statistics. Admin can also set a limit for each user a maximum number of entries a day.

Priority:
High

Estimation:
size: 35

Origin:
Feature Request

**Comment by TyRicard** [comment]
**The actual time spent completing this issue was 45 Story Points.**
