### ISSUE TITLE
"Create Account" Functionality not implemented

### ISSUE THREAD

**Issue by ntpimlott** [SENG426-Team/vega-web#35]
**Description:** 
A user should be able to register a new account while not logged in. After selecting the signup button the user will be led to a sign up page where the user will be able to register a new account with a unique, valid username and a valid password. Upon creation of the account, the system will consider the new user an inactivated customer account until the account is activated by an admin.

**Priority:** 
Medium

**Origin:** 
System Testing

**Comment by TyRicard** [comment]
**The actual time spent completing this issue was 30 Story Points.**
