### ISSUE TITLE
"Name" input box displays wrong error message

### ISSUE THREAD

**Issue by ntpimlott** [SENG426-Team/vega-web#39]
**Description:** 
Name error message should outline the limitations of the name input not email. User must enter a first name and last name. The first name can not exceed 50 characters, and the last name can not exceed 50 characters.

![Screen Shot 2022-05-25 at 12 53 04 PM](https://user-images.githubusercontent.com/68630621/170355876-a1a64447-f3fe-4207-b107-cf9bf9c716fb.png)

**Priority:** 
Low

**Origin:** 
System Testing

**Comment by joshmorg1007** [comment]
Note: this page is listed as [UserRegistration.js](https://github.com/SENG426-Team/vega-web/blob/master/src/components/pages/UserRegistration.js) for some reason.

**Comment by chloe-blankers** [comment]
The actual time spent on this issue was 7 story points
