### ISSUE TITLE
Admin should not be able to change its own role

### ISSUE THREAD

**Issue by joshmorg1007** [SENG426-Team/vega-web#40]
**Description:** 
The admin should be able to change the role of a registered User to "Staff" or "User" but should not be able to change its own role.

![Screen Shot 2022-05-27 at 2 28 31 PM](https://user-images.githubusercontent.com/68630621/170791583-76d65564-6ef0-4469-b6d7-56bd3112d47b.png)
![Screen Shot 2022-05-27 at 2 28 04 PM](https://user-images.githubusercontent.com/68630621/170791600-5cfbc8f0-1415-4858-adea-4bf689f21849.png)

**Priority:** 
Low

**Size estimation:** 
Size: 20

**Origin:** 
System Testing

**Comment by chloe-blankers** [comment]
**The actual time spent on this issue was 4 story points**
